# Generated by Django 5.0.2 on 2025-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_skill_teamproject_alter_user_role_enterpriseprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
