# Generated by Django 5.0.2 on 2025-02-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_taskexchange_student2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexchange',
            name='task2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
