# Generated by Django 5.0.2 on 2025-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseprofile',
            name='name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='web_site',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fullname',
            field=models.CharField(default='AMIRA MMR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(default='computer science', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_studying',
            field=models.CharField(default='3d', max_length=10),
            preserve_default=False,
        ),
    ]
