# Generated by Django 5.0.2 on 2025-02-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_studentprofile_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_studying',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
