# Generated by Django 5.0.2 on 2025-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_studentprofile_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, choices=[('ENP', 'ENP'), ('USTHB', 'USTHB'), ('ESI', 'ESI'), ('UMBB', 'UMBB'), ('Autre', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_studying',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
